name:       autoteka
version:    0.2.0.0
github:     "ruamk/autoteka"
license:    MIT
author:     "Max Taldykin"
maintainer: "jorpic@gmail.com"
copyright:  "2020 RAMC"

description: FIXME

extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -Werror
  - -O2
  - -funbox-strict-fields

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - TypeOperators
  - DataKinds

library:
  source-dirs: src
  dependencies:
    - base
    - text
    - time
    - aeson
    - servant
    - servant-client
    - http-client
    - http-api-data

executables:
  autoteka:
    main: Main.hs
    source-dirs: bin
    dependencies:
      - autoteka
      - aeson
      - base
      - http-client
      - http-client-tls
      - servant-client
      - text
      - time
    default-extensions:
      - LambdaCase
      - OverloadedStrings
